### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by md-rifatkhan** [alihadi5125/smooth_compass#10]
```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building FutureBuilder<bool>(dirty, state: _FutureBuilderState<bool>#13b2d):
Null check operator used on a null value

The relevant error-causing widget was: 
  FutureBuilder<bool> FutureBuilder:file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/smooth_compass-2.0.17/lib/utils/src/compass_ui.dart:53:12
When the exception was thrown, this was the stack: 
#0      _SmoothCompassState.build.<anonymous closure> (package:smooth_compass/utils/src/compass_ui.dart:63:29)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)

```

**Comment by korat2511** [comment]
I am also getting same issue, 
![WhatsApp Image 2024-08-22 at 02 25 14](https://github.com/user-attachments/assets/0361069c-71b1-4764-b42c-4b4bc35c463b)
