### ISSUE TITLE
closing app

### ISSUE THREAD

**Issue by mohammadLubbad-flutter** [alihadi5125/smooth_compass#8]
when use the package and run the app its directly closess the app with this error E/AndroidRuntime( 8462): FATAL EXCEPTION: main
E/AndroidRuntime( 8462): Process: com.example.islamna, PID: 8462
E/AndroidRuntime( 8462): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~C6dgEDxsN0geEpOpadlhxw==/com.example.islamna-zk9PJTDSXDgRTY-daJsK_A==/base.apk)
E/AndroidRuntime( 8462): 	at com.lyokone.location.FlutterLocation.startRequestingLocation(FlutterLocation.java:422)
E/AndroidRuntime( 8462): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:121)
E/AndroidRuntime( 8462): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
E/AndroidRuntime( 8462): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 8462): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 8462): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 8462): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 8462): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8462): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8462): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 8462): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 8462): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime( 8462): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8462): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 8462): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by mohammadLubbad-flutter** [comment]
notice that im using the same example in the package

**Comment by savitore** [comment]
@mohammadLubbad-flutter I'm getting the same error while using the package. The app crashes while using the app.
